version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.0-rc.3-management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
    - 5672:5672
    - 15672:15672

volumes:
  mongo-db: